  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: camera_support_joint # the same name of the joint used in the urdf file
    pid: {p: 2.0, i: 0.0, d: 0.0}
